services:
  - type: web
    name: yetcoins-tg-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false # Set this in the Render dashboard
      - key: RENDER_URL
        sync: false # Set this in the Render dashboard
      - key: PORT
        value: 3000
